-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : sam. 29 août 2020 à 19:08
-- Version du serveur :  10.4.11-MariaDB
-- Version de PHP : 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `vf_association`
--

-- --------------------------------------------------------

--
-- Structure de la table `evenement`
--

CREATE TABLE `evenement` (
  `id` int(11) NOT NULL,
  `titre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contenu` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `publier` tinyint(1) NOT NULL,
  `image_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `evenement`
--

INSERT INTO `evenement` (`id`, `titre`, `contenu`, `created_at`, `updated_at`, `publier`, `image_name`) VALUES
(1, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(3, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(4, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(5, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(6, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(7, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(8, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(9, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(10, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(11, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(12, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(13, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(14, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(15, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg'),
(16, 'Plan d’action sur les Droits Humains et le VIH en Tunisie', 'Une réunion extraordinaire a été organisée par le CCM, le 6 février 2020 dans les locaux de l’OMS à Tunis. L’objectif essentiel de cette réunion était de valider le Plan d’action sur les Droits Humains et le VIH pour la période 2019-2021. Ce Plan d’action qui est financé par le Fonds mondial, constitue une partie du Plan Stratégique National sur les Droits Humains et le VIH couvrant la période allant de 2019 à  2023.\r\n\r\nLa présentation de ce plan d’action, par le Récipiendaire Principal, a mis en évidence la répartition de ses différentes activités par domaine d’intervention et selon les axes prioritaires de ce plan. Un nouveau Sous Récipiendaire vient d’intégrer la liste des sous récipiendaires travaillant sur le VIH pour aider à la mise en oeuvre de cette subvention concernant les Droits Humains et le VIH.\r\n\r\nAu terme de cette réunion extraordinaire du CCM, ce Plan d’action sur les Droits Humains et le VIH (2019-2021) a été validé par le CCM et sera transmis au Fonds mondial pour son approbation.', '2020-08-25 19:47:00', '2020-08-25 19:56:36', 1, '20200206-104206-770x375-5f4550d4ad408821458585.jpg'),
(17, 'Le CCM-Tunisie œuvre pour promouvoir la participation et la coordination', 'Conscients de l’importance de la participation de la société civile particulièrement les populations clés et les PVVIH ainsi que les ONG aussi bien dans la planification des actions que dans la prise de décision, le CCM-Tunisie n’a pas cessé d’œuvrer pour améliorer la communication en son sein et de renforcer la coordination entre les différentes parties prenantes concernées par la riposte au VIH/sida.\r\n\r\nDans ce contexte, le CCM-Tunisie a organisé, au cours des mois de novembre-décembre 2019 et de janvier 2020, trois Workshop de formation sur les techniques de communication, trois ateliers inter-régionaux (à Tunis, à Sousse et à Sfax) sur la coordination entre les groupes constitutifs de la société civile du CCM, et également quatre réunions de suivi et de feedback avec des représentants des PVVIH, des populations clés et des ONG.\r\n\r\nL’objectif général de ces rencontres est de contribuer au renforcement de la communication, de la coordination et des circuits de l’information, notamment à l’échelle régionale, entre les associations, personnes vivant avec le VIH et les populations clés de la société civile pour une prise de décision participative au sein du CCM. Ces activités ont touché 210 participants dont 109 sont de sexe féminin contre 101 de sexe masculin.\r\n\r\nLors de ces rencontres, diverses questions ont été traitées telles que les forces et faiblesses de la communication, les fondements et principes de la coordination, les compétences des représentants élus des groupes constitutifs de la société civile et leurs responsabilités au sein du CCM, le processus électoral des représentants du secteur de la société civile au CCM…\r\n\r\nLes participants se sont inscrits avec beaucoup de motivations dans ces espaces de Dialogue. Ils ont échangé, discuté et défendus leurs opinions qui peuvent servir pour la prochaine subvention. Cet engagement témoigne de leur volonté de participer aux efforts déployés en Tunisie en matière de riposte au VIH/sida pour l’atteinte des trois objectifs 90-90-90.', '2020-08-25 20:17:00', '2020-08-25 20:17:00', 1, '85040580-478180273060566-4370731317965357056-n-770x375-5f4555b909ef6188458399.jpg');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `roles` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:json)',
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prenom` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_naissance` datetime DEFAULT NULL,
  `adresse` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `adherent` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `email`, `username`, `roles`, `password`, `nom`, `prenom`, `cin`, `date_naissance`, `adresse`, `job_title`, `description`, `adherent`) VALUES
(1, 'abdessalemkhaled@gmail.com', 'Khaled', '[\"ROLE_USER\",\"ROLE_ADMIN\",\"ROLE_EDITOR\"]', '$argon2id$v=19$m=65536,t=4,p=1$endaM2xjME1GZlRBdmRaNQ$Dd2KouGayJ1VHx3nfOe5IFyO4n19qVkGMzMyo4BxbxE', 'Abdessalem', 'Khaled', '08717494', '1988-09-01 00:00:00', '54 rue el kharj cité la santé borj louzir ariana', 'web', NULL, 1),
(2, 'user1@gmail.com', '12345678', '[\"ROLE_USER\",\"ROLE_EDITOR\"]', '$argon2id$v=19$m=65536,t=4,p=1$UXhuZWh2eEJ3TGxZTEpvNA$yJ/6HCN8h4Yh1Jl8HeWrve/phAX9qoasqj5jCi40nYk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(3, 'abdessalemkhaledd@gmail.com', 'Klod', '[\"ROLE_USER\"]', '$argon2id$v=19$m=65536,t=4,p=1$QlRnbmNQUVlCWVFkZUoxeQ$h962ZSymWERNyOQg3haWFoMvjTB2Gg9t5des3JxJS+g', 'Abdessalem', 'Khaled', '08717494', '2000-10-20 00:00:00', '54 rue el kharj cité la santé borj louzir ariana', NULL, NULL, 0),
(4, 'abdessalemkhaleddd@gmail.com', 'KH', '[\"ROLE_USER\"]', '$argon2id$v=19$m=65536,t=4,p=1$QlRnbmNQUVlCWVFkZUoxeQ$h962ZSymWERNyOQg3haWFoMvjTB2Gg9t5des3JxJS+g', 'Abdessalem', 'Khaled', NULL, '1919-03-17 00:00:00', '54 rue el kharj cité la santé borj louzir ariana', NULL, NULL, 1),
(5, 'khaled@gmail.com', 'Mohamed', '[\"ROLE_USER\"]', '$argon2id$v=19$m=65536,t=4,p=1$bmdqZGdMQUhOS3k4SHpxNA$IpfHJ/R17637+sTiWy0bZdPjGxX/rBlttHLG7ko73Ck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `evenement`
--
ALTER TABLE `evenement`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQ_1483A5E9E7927C74` (`email`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `evenement`
--
ALTER TABLE `evenement`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
